CheckMate-sookmyung/CheckMate-client

- .github/CODEOWNERS
> Feat: #8 reviewer 자동 설정

- src/pages/AttendancePage/AttendancePage.jsx
- src/pages/AttendancePage/AttendancePage.style.jsx
- src/pages/AttendancePage/index.js
- src/pages/index.js
> Feat: 출석체크 페이지(학번) view 개발

- src/pages/SignPage/SignPage.jsx
- src/pages/SignPage/SignPage.style.jsx
- src/pages/SignPage/index.js
- src/pages/index.js
> Feat: #3 서명 페이지 개발

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/components/AttendanceHeader/index.js
- src/components/Step/Step.style.jsx
- src/components/Stepper/Stepper.style.jsx
- src/components/index.js
- src/icons/CloseIcon/CloseIcon.jsx
- src/icons/CloseIcon/index.js
- src/icons/index.js
- src/pages/AttendancePage/AttendancePage.jsx
- src/pages/AttendancePage/AttendancePage.style.jsx
- src/pages/SignPage/SignPage.jsx
- src/pages/SignPage/SignPage.style.jsx
> Feat: #3 출석 페이지내 헤더 컴포넌트 개발

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/pages/AttendancePage/AttendancePage.jsx
- src/pages/AttendancePage/AttendancePage.style.jsx
#3 
- 학번 7자리를 모두 입력하지 않은 경우 (확인 버튼 비활성화)
- 학번 7자리를 모두 입력한 경우
> Feat: #3 출석체크 화면에 헤더 컴포넌트 적용

- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
- src/components/Modal/index.js
- src/components/index.js
- src/icons/CheckBoxIcon/CheckBoxIcon.jsx
- src/icons/CheckBoxIcon/index.js
- src/icons/CheckboxCheckedIcon/CheckboxCheckedIcon.jsx
- src/icons/CheckboxCheckedIcon/index.js
- src/icons/index.js
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
#4
- 서명하러가기 버튼 비활성화
- 서명하러가기 버튼 활성화
> Feat: 본인 확인 모달창 구현

- src/components/calendar/DateCalendar.jsx
- src/pages/registerPage/register.jsx
- src/router.js
#22 
register 페이지 라우터 추가
register 페이지 value 받아오기
date 캘린더 값 받아오기
> feat: 날짜 받아오기

- src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
- src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
- src/components/AttendanceConfirmModal/index.js
- src/components/index.js
- src/icons/AttendanceConfirmIcon/AttendanceConfirmIcon.jsx
- src/icons/AttendanceConfirmIcon/index.js
- src/icons/index.js
> Feat: #4 모달 창 개발 (출석 완료)

- src/components/Background/BackgroundPage.jsx
- src/components/calendar/DateCalendar.jsx
- src/components/calendar/DateCalendarStyle.js
- src/pages/registerPage/register.jsx
#22 
행사 캘린더 디테일 + 행사 일정 받아오기
시간만 구현하면 행사 등록 페이지 구현 완성~
> feat: 캘린더 행사 일정 연결

- src/components/Background/BackgroundPage.jsx
- src/pages/EventList/currentEvent.jsx
- src/router.js
> feat: 진행중인 행사 페이지

- package.json
- src/pages/EventList/currentEvent.jsx
> feat: 진행중인 행사 API 연결

- package-lock.json
- package.json
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
#3
- 서명 전 (버튼 비활성화)
- 서명 후 (버튼 활성화)
> Feat: #3 전자 서명 기능 구현

- public/index.html
- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
- src/components/Portal/Portal.jsx
- src/index.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
> Feat: #41 본인 확인 모달창 구현

- .gitignore
- src/axios/axiosInstance.js
- src/axios/index.js
- src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/pages/EventList/currentEvent.jsx
- src/services/attendanceService/attendanceService.js
- src/services/attendanceService/index.js
- src/services/index.js
> Feat: #42 API 일부 연결

- src/pages/EventDetail/AttendenceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/pages/registerPage/register.jsx
- src/router.js
#행사 후
현재 진행중인 이벤트 -> 행사 상세 페이지 -> 행사 출석 명단 목록
> feat: 현재 이벤트 - 출석 리스트

- src/pages/EventList/currentEvent.jsx
#37 
행사 리스트 -> 출석체크 버튼 -> 학번 입력 페이지 이동
> fix: 라우팅 추가

- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
> Refactor: #50 상수값 관리 방식 수정

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/AttendanceHeader/AttendanceHeader.style.jsx
> Feat: #52 닫기 버튼 구현

- src/pages/EventDetail/AttendenceList.jsx
- src/pages/EventList/currentEvent.jsx
#37 
진행 중 행사 목록, 행사 명단 반환 공용 인스턴스 사용으로 변경
변경된 API 구조 맞춰 수정
행사 리스트 함수 변경
> fix: API 구조 수정, 명단 싸인 출력, 인스턴스 변경

- src/pages/EventDetail/eventDetail.jsx
#37 
행사 상세 페이지 API 연결 
* 상세 페이지에 꼭 들어가야하는 내용 여부 / 우측 상단 서브메뉴 형태 추후 논의 필요
> feat: 이벤트 디테일 API 연결

- src/Layout/Layout.jsx
- src/components/Background/BackgroundPage.jsx
- src/components/navigator.jsx
- src/pages/registerPage/register.jsx
- src/router.js
#22 
네비게이션 로직 구현, 클릭 시 스타일 변경 
라우팅 변경
> feat: 네비바 라우터 연결

- src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
- src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/services/attendanceService/attendanceService.js
> design: api 일부 수정 및 모달 디자인 변경

- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/pages/registerPage/register.jsx
> fix: #63 api 수정

- src/components/Background/BackgroundPage.jsx
- src/components/navigator.jsx
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/router.js
#37 
행사 상세 내용 구조 수정, 디자인 수정
행사 명단 전송 API 버튼 추가
네비게이션 라우팅 방법 수정
상세 페이지 주소 수정
> fix: 행사 상세, 명단 수정

- src/constants/tempData.js
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
#63 
- 학번 입력 페이지 반영
- 서명 페이지 반영
> design: 헤더 컴포넌트 내 api 수정

- src/components/Background/BackgroundPage.jsx
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/registerPage/register.jsx
백그라운드 ui 변경
명단 리턴 스크롤
등록 페이지 플레이스홀더
> fix: 디자인 오류 수정

- src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
- src/constants/tempData.js
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventList/currentEvent.jsx
> fix: #69 사용자 테스트를 위한 이벤트 아이디 등 수정

- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
> design: #72 출석체크 화면 내 다이얼 배치 수정

- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
> feat: #62 예외처리 (이미 출석 완료, 없는 학번)

- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
> design: #72 출석체크 화면 디자인 재수정

- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
#72
🚨 참고: 서버 이슈로 일부 코드 주석처리
- 구현 화면
> style: #72 폰트, 컬러, margin 등 디테일 수정

- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
> fix: 다이얼 0 안눌림 문제 해결

- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
> fix: 출석 API 연결

- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
- src/pages/EventDetail/AttendanceList.jsx
#72
- 출석체크 헤더 내 close incon 위치 조정
- 비활성화 버튼 수정 및 출석명단 확인을 위한 배열 수정
> style: #72 ui-detail 수정

- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/styles/CheckMateStyles.style.jsx
#37 
행사 일정 인덱스 수정
행사 상세 페이지 디자인 수정
행사 출석 명단 디자인 수정
- 이 과정에서 전역 디자인 추가
> fix: 이벤트 디테일, 출석 명단 수정

- src/pages/registerPage/register.jsx
#이슈번호
백그라운드 컴포넌트를 행사 등록 페이지에 적용으로 코드 간소화
> refactor: 배경 재사용 코드 간소화

- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/constants/tempData.js
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
- src/styles/index.js
- src/styles/mediaQueries.style.js
#87 
🚨 참고) 라이브러리를 사용한 canvas 반응형은 추후 구현 예정
- 반응형
-  다이얼 높이 조정
- 서명안내 문구 크기 조정
> feat: #87 학번 입력, 서명 페이지 반응형 구현 및 피드백 반영

- src/components/Calendar/DateCalendar.jsx
- src/components/Calendar/DateCalendarStyle.js
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/registerPage/register.jsx
#이슈번호
포스터 위치를 명단으로 대체
총인원/참석/불참 볼 수 있는 칸
출석 메일 전송 확인창을 거칠 수 있도록 수정
> 포스터 위치 명단 대체, 날짜 캘린더, 백그라운드 수정

- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.jsx
- src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
- src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
> modify: #87 서명 페이지 모바일 반응형 구현 완료

- src/components/navigator.jsx
- src/pages/EventList/currentEvent.jsx
> modify: #87 행사목록 페이지 반응형 재구현

- package.json
- src/components/Calendar/DateCalendar.jsx
- src/index.jsx
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/recoil/atoms/state.js
#98 
recoil 상태관리 라이브러리 다운
recoil 폴더 추가
행사 목록, 상세 페이지, 출석명단 API 전역으로 상태 관리
> feat: 상태관리 추가

- package.json
- src/components/Calendar/DateCalendar.jsx
- src/components/navigator.jsx
- src/index.jsx
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/recoil/atoms/state.js
> dev to main

- public/index.html
- src/components/Background/BackgroundPage.jsx
- src/components/Calendar/DateCalendar.jsx
- src/components/Calendar/TimeCalendar.jsx
- src/components/navigator.jsx
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/eventDetail.jsx
- src/pages/EventList/currentEvent.jsx
- src/pages/registerPage/register.jsx
> modify: #87 행사 등록페이지 반응형 구현

- src/components/Calendar/DateCalendar.jsx
- src/components/Calendar/DateCalendarStyle.js
- src/components/Calendar/TimeCalendar.jsx
- src/components/Calendar/TimeCalendarStyle.js
#이슈번호
날짜캘린더 버튼 삭제
시간캘린더 코드 분리 및 일부 삭제
> Fix: 캘린더 수정사항

- src/pages/Home/Home.jsx
- src/pages/Home/HomeCarousel/HomeCarousel.jsx
- src/pages/Home/HomeStyle.js
- src/router.js
#110 
홈화면 기본 UI 생성 (세부 디자인은 추후 추가)
> Feat: 홈화면 구현

- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/pages/DashboardPage/index.js
- src/pages/index.js
- src/router.js
> feat: #113 대시보드 페이지 view 구현

- package-lock.json
- package.json
- src/pages/DashboardPage/DashboardInfo.jsx
- src/pages/DashboardPage/DashboardInfo.style.jsx
- src/pages/DashboardPage/index.js
- src/pages/index.js
- src/router.js
#113
- 행사 기본 정보 페이지 생성
- `DatePicker` 라이브러리를 홡용한 날짜와 시간 기능 구현
- `toggle`을 활용한 온라인/오프라인 선택 기능 구현
- `radio button`을 활용해 행사 대상 선택 기능 구현
> feat: #113 행사 기본 정보 페이지 생성

- src/pages/DashboardPage/DashboardEmail.jsx
- src/pages/DashboardPage/DashboardEmail.style.jsx
- src/pages/DashboardPage/DashboardInfo.jsx
- src/pages/DashboardPage/DashboardInfo.style.jsx
- src/pages/DashboardPage/index.js
- src/pages/index.js
- src/router.js
#113
- 전체 발송 옵션 선택시, 수신자 선택 항목 가림
- 이메일 내용 템플릿
> 안녕하세요, [기관명]입니다.
> 
> [행사명]을 진행합니다.
> 
> - 일시: YYYY-MM-DD HH:MM
> - 대상: 전체/일부
> - 내용: 이메일 본문 내용
> 
> 기타 궁금한 사항이 있으시면 언제든지 문의해주시기 바랍니다.
> 
> 감사합니다.
- 구현 화면 (전체 발송)
- 구현 화면 (일부 발송)
> feat: #113 이메일 예약 발송 페이지 구현

- src/pages/DashboardPage/DashboardAttendee.jsx
- src/pages/DashboardPage/DashboardAttendee.style.jsx
- src/pages/DashboardPage/index.js
- src/pages/index.js
- src/router.js
> feat: #113 참석자 관리 페이지 구현

- src/Layout/Layout.jsx
- src/components/Navigator/Navigator.jsx
- src/components/Navigator/Navigator.style.jsx
- src/components/Navigator/Sidebar.jsx
- src/components/Navigator/Sidebar.style.jsx
- src/components/Navigator/index.js
- src/components/index.js
- src/pages/DashboardPage/DashboardAttendee.style.jsx
- src/pages/DashboardPage/DashboardEmail.style.jsx
- src/pages/DashboardPage/DashboardInfo.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/router.js
> feat: #107 사이드바 구현

- src/Layout/Layout.jsx
- src/Layout/PageLayout.jsx
- src/pages/DashboardPage/DashboardAttendee.jsx
- src/pages/DashboardPage/DashboardEmail.jsx
- src/pages/DashboardPage/DashboardInfo.jsx
- src/pages/DashboardPage/DashboardPage.jsx
#107
-  대시보드 페이지에만 사이드바 보이도록 수정
> feat: #107 대시보드 페이지에만 사이드바 보이도록 수정

- package.json
- src/recoil/atoms/state.js
#98 
- 행사 상세 페이지 조회 시 Recoil - persist 추가
> Feat:recoil-persist 추가

- src/Layout/Layout.jsx
- src/Layout/PageLayout.jsx
- src/components/Navigator/Navigator.style.jsx
- src/components/Navigator/Sidebar.style.jsx
- src/pages/DashboardPage/DashboardAttendee.jsx
- src/pages/DashboardPage/DashboardAttendee.style.jsx
- src/pages/DashboardPage/DashboardEmail.jsx
- src/pages/DashboardPage/DashboardEmail.style.jsx
- src/pages/DashboardPage/DashboardInfo.jsx
- src/pages/DashboardPage/DashboardInfo.style.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/pages/EventDetail/EventDetailPage.jsx
> modify: #107 페이지 하단 및 기타 여백 조정

- package-lock.json
- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/Navigator/Navigator.style.jsx
- src/pages/Home/Home.jsx
- src/pages/Home/HomeStyle.js
> modify: #87 테스트를 위한 반응현 구현 및 홈 화면 일부 수정

- src/components/Button/BlueButton90.jsx
- src/components/Button/GrayButton90.jsx
- src/components/Button/TabButton90.jsx
- src/components/Button/index.js
- src/components/index.js
- src/pages/DashboardPage/DashboardAttendee.jsx
- src/pages/DashboardPage/DashboardAttendee.style.jsx
- src/pages/DashboardPage/DashboardEmail.jsx
- src/pages/DashboardPage/DashboardEmail.style.jsx
- src/pages/DashboardPage/DashboardInfo.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/styles/CheckMateStyles.style.jsx
#126
- 전역 컬러 적용 (임시)
- `src` - `styles` - `CheckMateStyles.style.jsx`
- 사용 예시:  `color: var(--gray-300, #636363)`
- 버튼 컴포넌트 생성
- `BlueButton90`  `GrayButton90`  `TabButton90`
> feat: #126 [공통] 컴포넌트 생성 및 전역 스타일 적용

- src/constants/tempData.js
- src/pages/EventList/EventList.jsx
#130
- 사용자 테스트를 위한 상수값 수정
- 최신순으로 행사 목록 정렬
> hotfix: #130 사용자 테스트를 위한 상수값 수정 및 최신순으로 행사 목록 정렬

- src/constants/tempData.js
- src/pages/EventDetail/AttendanceList.jsx
- src/pages/EventDetail/EventDetailPage.jsx
- src/pages/EventDetail/EventDetailPage.style.jsx
#130
- 사용자 테스트를 위한 상수값 수정
- 상세 페이지 내 페이지 이동 버튼 추가
> merge: hotfix/event-id to main

- README.md
#133
- Tech Stacks 업데이트
- Git Convention 업데이트
> docs: #133 README.md 수정

- src/pages/DashboardPage/DashboardAttendee.jsx
- src/pages/DashboardPage/DashboardAttendee.style.jsx
- src/pages/DashboardPage/SessionDateTab.jsx
#113
- 출석 여부 수정 모드 구현
- 회차 탭메뉴 컴포넌트 분리
- 데이터 기반으로 출석률 반영하는 기능 구현
- 기본 모드
- 수정 모드
> feat: #113 참석자 관리 페이지 내 기능 구현

- src/pages/EventList/EventList.jsx
- src/pages/EventList/EventListStyle.js
- 출석 체크 버튼이 올라가는 부분 수정
- 버튼 컬러 수정 및 hover 효과 적용
- 일정부분 폰트 컬러 수정
- 행사 포스터 상단부터 보이도록 수정 (포스터 내 행사명 잘렸던 부분 개선)
> design: 출석 체크 버튼이 올라가는 부분 및 컬러 등 디테일 수정

- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
#113
- 이름 오름차순을 기본 설정으로
- 불필요한 태그 삭제
> #113 feat: 참석자 관리 페이지 내 이름 오름차순으로 기본 설정

- src/pages/EventList/EventCard.jsx
- src/pages/EventList/EventCard.style.jsx
- src/pages/EventList/EventList.jsx
- src/pages/EventList/EventList.style.jsx
- src/pages/EventList/EventListStyle.js
- src/pages/EventList/index.js
#142
- 최신 행사가 앞에 오도록 수정
- 행사 종료시 버튼 내용과 색상 변경 및 비활성화
- 이벤트 카드 컴포넌트 분리
> #142 feat: 최신 행사가 앞에 오도록 수정

- src/components/Navigator/Navigator.jsx
- src/components/Navigator/Navigator.style.jsx
#144
- 상단 메뉴에 행사 제목 띄우는 API 연동
- navigate 대신 link태그로 페이지 이동하도록 수정
> #144 feat: 상단 메뉴에 행사 제목 띄우는 api 연동

- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
#113
- 행사 상태에 따른 뱃지 색상 및 내용 변동 (종료/진행중/예정)
> #113 feat: 행사 상태에 따른 뱃지 색상 및 내용 변동

- src/components/Navigator/Navigator.style.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
#62
- 없는 학번일 경우 alert창 띄우기
- 컨텐츠간 간격 조정
> #62 fix: 없는 학번일 경우 alert창 띄우기

- src/pages/AttendancePage/AttendanceSignPage.jsx
- src/pages/AttendancePage/AttendanceSignPage.style.jsx
#137
- 서명 페이지 헤더에 행사 타이틀 가져오는 API 수정
- 불필요한 코드 삭제 및 canvas 비율 수정
> #137 fix: 서명 페이지 헤더에 행사 타이틀 가져오는 API 수정

- src/components/Navigator/Navigator.jsx
- src/components/Navigator/Navigator.style.jsx
- src/components/Navigator/Sidebar.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
- src/pages/DashboardPage/DashboardEmailPage.style.jsx
- src/pages/DashboardPage/DashboardInfoPage.style.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
#이슈144번호
- 모바일 반응형시 햄버거 메뉴가 생성되는 기능 구현
(기존 페이지에서 사이드바가 사라지는 기능은 곧 구현 예정)
> #144 feat: 모바일 반응형시 햄버거 메뉴가 생성되는 기능 구현

- src/pages/RegisterPage/RegisterComponents/BackButton.jsx
- src/pages/RegisterPage/RegisterComponents/DragnDrop.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterFirst.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
- src/pages/RegisterPage/RegisterComponents/RegisterThird.jsx
- src/pages/RegisterPage/RegisterPage.jsx
- src/pages/RegisterPage/RegisterStyle.js
- src/recoil/atoms/state.js
- src/recoil/atoms/useResetAllState.js
#111 
- 뒤로가기 버튼 추가
- 사이드바 추가
- 드래그앤드랍 일부 수정
- state 구조 변경 / reset state 추가
- 일부 디자인 변경
> feat: 뒤로가기 버튼 추가

- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
> #113 feat: 참석자 목록 페이지 내 전화 기능 구현

- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
> feat: 담당자 이름 입력창 생성 및 API 연동

- src/pages/DashboardPage/DashboardAttendeePage.jsx
#113
- 참석자 명단 다운로드 받는 코드 추가
🚨 다운로드만 가능한 상태이고, 파일이 열리지 않는 문제는 서버측과 논의 필요
> #113 feat: 참석자 명단 다운로드 받는 코드 추가

- src/pages/DashboardPage/DashboardInfoPage.jsx
- src/pages/DashboardPage/DashboardInfoPage.style.jsx
#160
- 반대로 되어있던 eventTarget 수정
> #160 fix: 반대로 되어있던 eventTarget 수정

- src/pages/AttendancePage/AttendanceStudentIdPage.jsx
> #159 modify: EVENT_DATE import문 삭제

- package-lock.json
- src/constants/tempData.js
> #164 fix: 배포 오류 해결

- src/pages/DashboardPage/DashboardAttendeePage.jsx
#168  
- 참석여부 수정 API 연동
-  모든 탭 내 이름 오름차순이 되도록 설정
> #168 fix: 참석여부 수정 API 연동

- src/Layout/PageLayout.jsx
- src/components/Navigator/Navigator.jsx
- src/components/Navigator/Navigator.style.jsx
- src/components/Navigator/Sidebar.jsx
- src/components/Navigator/Sidebar.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
#144
- 대시보드 > 담당자 내 tooltip 문구 수정
- 행사 진행 중일경우에만 '출석화면으로 이동' 버튼 활성화
- 모바일 사이즈로 화면사이즈가 줄어들면, 왼쪽 sidebar 사라지는 코드 추가
- 사이드바 이외의 영역에 dim 처리 및 스크롤 다운시 사이드바 사라짐
> #144 modify: 모바일 사이즈로 화면사이즈가 줄어들면, 왼쪽 sidebar 사라지도록 구현

- src/components/Modal/Modal.jsx
- src/pages/AttendancePage/AttendanceSignPage.jsx
- src/pages/AttendancePage/AttendanceSignPage.style.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.jsx
#172
- eventTarget이 외부인인 경우 휴대폰 번호 뒷 4자리로 출석체크
- 현재 날짜로 출석체크 되는 기능 구현
- 외부인을 대상으로 하는 행사의 경우, 서명 페이지에 소속만 보여줌
- 휴대폰 번호 뒷 4자리가 동일한 사람이 있는 경우 모달창 띄우는 기능 구현
- 휴대폰 번호를 문자로 변환해서 데이터 전송
- 서명 페이지 내 canvas 비율 조정 및 소속 간격 조정
> #172 feat: eventTarget이 외부인인 경우 휴대폰 번호 뒷 4자리로 출석체크

- src/pages/AttendancePage/AttendanceSignPage.style.jsx
> #164 fix: 서명페이지 내 서명칸 사이즈 확대

- src/components/Navigator/Sidebar.jsx
- src/pages/AttendancePage/AttendanceSignPage.style.jsx
- src/pages/EventList/EventCard.jsx
- src/pages/EventList/EventCard.style.jsx
> #164 style: 행사 목록 내 행사 예정 버튼 색상 적용

- src/components/Modal/Modal.jsx
- src/pages/AttendancePage/AttendanceSignPage.jsx
- src/pages/AttendancePage/AttendanceSignPage.style.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.jsx
- src/pages/EventList/EventCard.jsx
- src/pages/EventList/EventCard.style.jsx
#164
- 날짜 라이브러리 사용
- 행사 목록 내 버튼 재설정
- 서명 축소되는 문제 해결
- 출석체크 오류 해결
> #164 fix: 출석체크 오류 해결

- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
- src/components/Navigator/Sidebar.jsx
- src/constants/tempData.js
- src/pages/DashboardPage/DashboardPage.style.jsx
#164
- 뱃지 크기 수정 및 대시보드 페이지 내 출석체크 버튼 재활성화
- 모달 창 내 이름 불러오도록 코드 수정 
- 모달 창 backdrop 설정
- USER_ID 수정
> #164 fix: USER_ID 수정

- src/pages/DashboardPage/DashboardPage.jsx
> #164 remove: 출석명단 자동 전송 코드 임시 삭제

- src/constants/tempData.js
> #189 modify: USER_ID를 테스트 버전으로 변경

- src/constants/tempData.js
- src/pages/DashboardPage/DashboardPage.jsx
> #189 merge: dev to main

- src/pages/DashboardPage/DashboardAttendeePage.jsx
#이슈번호
- 참석자 명단 리스트에서 표제목 일부 변경
> modify: 참석자 명단 리스트에서 표제목 일부 변경

- src/components/Button/BlueButton/BlueButton.jsx
- src/components/Button/BlueButton/BlueButtonStyle.jsx
- src/components/Button/GrayButton/GrayButton.jsx
- src/components/Button/GrayButton/GrayButtonStyle.jsx
- src/components/Button/index.js
- src/pages/DashboardPage/DashboardPage.jsx
#197
- 버튼 컴포넌트 생성 및 대시보드 페이지에 일부 적용
> #197 feat: 버튼 컴포넌트 생성 및 대시보드 페이지에 일부 적용

- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
> #199 modify: 대시보드 페이지 일부 수정

- src/components/Navigator/Navigator.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
- src/pages/TotalStatisticsPage/index.js
- src/pages/index.js
- src/router.js
#205
<br>
- 헤더메뉴 수정 및 통계페이지 생성
<br>
> #205 modify: 헤더메뉴 수정 및 통계페이지 생성

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.style.jsx
- src/components/Dropdown/index.js
- src/components/EventCard/EventCard.jsx
- src/components/EventCard/EventCard.style.jsx
- src/components/index.js
- src/pages/EventCardListPage/EventCardListPage.jsx
- src/pages/EventCardListPage/EventCardListPage.style.jsx
- src/pages/EventCardListPage/index.js
- src/pages/EventListPage/index.js
- src/pages/index.js
- src/router.js
#208
<br>
- 이벤트 카드 컴포넌트 스타일 수정
- 이벤트 목록 페이지 스타일 수정
- 토글 컴포넌트 생성
- 토글 컴포넌트를 이벤트 목록 페이지 내 배치
<br>
| 이벤트 목록 페이지 |
|<img width='600' src='https://github.com/user-attachments/assets/d333dd5c-91d9-44a0-87b5-7cd39eb088dc'>|
<br>
> #208 style: 행사 목록 페이지 수정 및 토글, 행사 카드 컴포넌트 생성

- src/components/EventCard/EventCard.style.jsx
#208
<br>
- 버튼 및 카드 테두리 스타일 수정
<br>
| 이벤트 목록 페이지 |
|<img width='600' src='https://github.com/user-attachments/assets/020d44b9-f516-4668-90c8-77a1ccd4b1c7'>|
<br>
> #208 style: 버튼 및 카드 테두리 스타일 수정

- src/components/Sidebar/Sidebar.jsx
- src/pages/DashboardPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardEmailPage.style.jsx
- src/pages/DashboardPage/DashboardInfoPage.jsx
- src/pages/DashboardPage/DashboardInfoPage.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
#199
<br>
- 대시보드 페이지 이전 스타일 적용
- 버튼 컴포넌트 적용
- 버튼을 하단 페이지로 이동
<br>
| PC 화면 |
|<img width='600' src='https://github.com/user-attachments/assets/7d29a4be-82be-4f3d-b012-6cca53ea468f'>|
<br>
> #199 design: 대시보드 페이지 이전 스타일 적용 및 디테일 수정

- src/components/TopNavigation/TopNavigation.jsx
- src/components/TopNavigation/TopNavigation.style.jsx
#215
<br>
- `Top Navigation` 내 max-width 해제
<br>
> #215 design: `Top Navigation` 내 max-width 해제

- src/components/ScrolltoTop/ScrolltoTop.jsx
- src/index.jsx
- src/pages/RegisterPage/PageComponents/RegisterCompleted.style.js
- src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
- src/pages/RegisterPage/RegisterComponents/EventTypeCard/EventTypeCard.jsx
- src/pages/RegisterPage/RegisterComponents/Scheduler/Scheduler.jsx
- src/pages/RegisterPage/RegisterComponents/Scheduler/Scheduler.style.js
- src/pages/RegisterPage/RegisterPage.jsx
#202 
<br>
- 사이드바 추가
- UI 일부 수정
- 배경 수정
- 페이지 상단 컴포넌트 추가
- 행사등록 컴포넌트 추가
<br>
<br>
> #202 modify: 행사 등록 페이지 컴포넌트 및 디자인 수정

- src/components/Button/Button.jsx
- src/components/Button/Button.style.jsx
- src/components/TabMenu/TabMenu.jsx
- src/components/TabMenu/TabMenu.style.jsx
- src/components/TabMenu/index.js
- src/components/index.js
- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardMessagePage.jsx
#223
<br>
- tab menu 컴포넌트 생성
- button 컴포넌트 스타일 수정
<br>
> #223 design: tab menu, button 컴포넌트 스타일 수정

- public/img/background-attendance.svg
- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
#227
<br>
- 출석체크 페이지 내 헤더 스타일 수정
- stepper 제거
- 배경 이미지 적용
- 컨텐츠 디자인 수정
<br>
| 휴대폰 번호 뒷자리 4자리 입력 |
|<img width='600' src='https://github.com/user-attachments/assets/5c556354-6a31-4ed1-9fed-910895fbed8c'>|
| 학번 입력 |
|<img width='600' src='https://github.com/user-attachments/assets/6739300f-c998-4e05-997f-0cbd0886865a'>|
| 학번 입력 (모바일 ver.)| 학번 입력 (모바일 ver.)|
|:----------------:|:----------------:|
|<img width='250' src='https://github.com/user-attachments/assets/8cc4c4f1-25a3-41e4-b537-59dcb20ba1f0'>|<img width='250' src='https://github.com/user-attachments/assets/03642918-edc7-4519-a56a-18433412c52f'>|
<br>
> #227 design: 출석체크 화면 디자인 수정

- .github/ISSUE_TEMPLATE/이슈-템플릿.md
- src/components/Table/AttendeeTable.jsx
- src/pages/DashboardPage/DashboardAttendeePage.jsx
#233
<br>
- 이슈 템플릿 수정
- 외부인 행사의 경우 테이블에서 학번, 학년 정보 제외시키기
<br>
|     외부인 행사 (학번, 학년 정보 삭제)     |
| <img width='600' src='https://github.com/user-attachments/assets/ce8532c2-5b35-4cfc-bcce-a5c8f81bba0f'> |
|     내부인 행사     |
| <img width='600' src='https://github.com/user-attachments/assets/d046f021-3ac9-4459-aefa-6a4bfdcce60f'> |
<br>
> #233 feat: 외부인 행사의 경우 테이블에서 학번, 학년 정보 제외시키기

- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.style.jsx
#227
<br>
- 본인 확인 모달 디자인 수정 
- 모바일 반응형 적용
<br>
|     PC사이즈    |
| <img width='600' src='https://github.com/user-attachments/assets/a685d8fd-d885-42dd-a39b-0e2753e98428'> |
|   모바일사이즈내용입력   |   
| :----------------------: | 
| <img width='250' src='https://github.com/user-attachments/assets/aca0f533-defc-42a0-8404-198faee02f8f'> | 
<br>
> #227  design: 본인 확인 모달 디자인 수정

- src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
#227
<br>
- 숫자 입력 칸 너비 늘리기
<br>
| 휴대폰 번호 뒷자리 4자리 입력 |
|<img width='600' src='https://github.com/user-attachments/assets/50ec105c-9879-40df-8770-81a452f25b83'>|
| 학번 입력 |
|<img width='600' src='https://github.com/user-attachments/assets/70a28b44-fb57-4a46-b728-1a2e8f68fbe3'>|
<br>
> #227 design: 숫자 입력 칸 너비 늘리기

- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
#202
<br>
- 교내 행사 : 학번 템플릿 / 교외 행사 : 번호 템플릿 나오도록 수정
<br>
<br>
> fix: #202 행사 등록용 템플릿 변수 오류 수정

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/AttendanceHeader/AttendanceHeader.style.jsx
- src/constants/tempData.js
- src/pages/AttendancePage/AttendanceSignPage.style.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
#227
<br>
- 서명 라이브러리 수정
- user id 수정
<br>
- 폰트사이즈 조절 외 변동 사항 없음
<br>
> #227 fix: 서명 라이브러리 수정 및 user id 수정

- src/components/DaterangePicker/DaterangePicker.jsx
- src/components/DaterangePicker/DaterangePicker.style.js
- src/components/DaterangePicker/index.js
- src/components/GraphBox/GraphBox.jsx
- src/components/GraphBox/GraphBox.style.js
- src/components/GraphBox/index.js
- src/components/index.js
#247
<br>
-행사 기간 컴포넌트
- 그래프 박스 컴포넌트
<br>
| ![image](https://github.com/user-attachments/assets/e3a110dc-7c2a-46b3-b6cd-2938c813a076)|
| ![image](https://github.com/user-attachments/assets/b41f97c5-67a6-4ce0-82d4-337a956b2ce3) | <img width='250' src=''> |
<br>
> feat: 통계 페이지 컴포넌트 구현

- src/components/EventTypeCard/index.js
- src/components/index.js
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
- src/pages/DashboardPage/DashboardInfoPage.style.jsx
- src/pages/DashboardPage/DashboardMessagePage.style.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
#227
<br>
- dashboard page layout
<br>
> #227 design: dashboard page layout

- src/components/Search/Search.jsx
- src/components/Search/Search.style.js
- src/components/Search/index.js
- src/components/index.js
- src/pages/EventCardListPage/EventCardListPage.jsx
#235 
<br>
-행사 목록에 검색 기능 구현
<br>
| ![chrome-capture-2024-9-6](https://github.com/user-attachments/assets/3aade7f0-9176-455a-96ab-6092ee4e5077) |
<br>
> feat: #235 행사 목록 검색 기능 구현

- src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
#250
<br>
- register page 내 사이드바 수정 (폰트, 간격 등)
<br>
| <img width='600' src='https://github.com/user-attachments/assets/48be4422-5f4e-48cc-b694-81cfb55c5a6f'> |
<br>
> #250 design: register page 내 사이드바 수정

- src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
#250
<br>
- 행사 등록 페이지 내 일부 폰트 크기 조정 및 줄 간격 조정
<br>
| <img width='600' src='https://github.com/user-attachments/assets/ab18c58b-0608-4a91-bc62-7716f3fb6b89'> |
<br>
> #250 design: 행사 등록 페이지 내 일부 폰트 크기 조정 및 줄 간격 조정

- src/components/Button/SlimButton.jsx
- src/components/Button/SlimButton.style.jsx
- src/components/Button/index.js
- src/components/EventTargetOption/EventTargetOption.jsx
- src/components/EventTargetOption/EventTargetOption.style.jsx
- src/components/Input/Input.style.jsx
- src/components/Scheduler/Scheduler.jsx
- src/components/Scheduler/Scheduler.style.js
- src/components/Textarea/Textarea.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
- src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
- src/pages/RegisterPage/PageComponents/RegisterPage.style.js
- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
- src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
- src/pages/RegisterPage/RegisterComponents/UploadBox/UploadBox.style.js
#250
<br>
- 본문 내용 가운데 정렬
- slimButton 컴포넌트 생성 및 적용
- 스케줄 스타일 수정
- 사이드바 border 수정
<br>
|     등록 첫 페이지    |
| <img width='600' src='https://github.com/user-attachments/assets/91bc0778-b603-4c10-abe1-20ceda180f7b'> |
|     등록 두 번째 페이지     |
| <img width='600' src='https://github.com/user-attachments/assets/be3192f2-6f0b-4b15-8b8c-c7407b0a0585'> |
<br>
> #250 design: 등록 페이지 내 스타일 수정

- src/components/Search/Search.jsx
- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage.style.jsx
#256
<br>
- search component props 수정 및 참석자 관리 페이지에 적용
<br>
| <img width='600' src='https://github.com/user-attachments/assets/8222195c-28ff-4c09-b0ff-0ae1e1bdfd63'> |
<br>
> #256 modify: search component props 수정 및 참석자 관리 페이지에 적용

- src/pages/Home/Home.Style.js
- src/pages/Home/Home.jsx
#259
<br>
- 홈 화면 내 행사 수, 출석 완료 인원수 API 연동
<br>
|    홈 화면 (일부)     |
| <img width='600' src='https://github.com/user-attachments/assets/f9df7ee7-73f3-4ef3-8f2b-00a4505d221e'> |
<br>
> #259 feat: 홈 화면 내 행사 수, 출석 완료 인원수 API 연동

- src/components/TopNavigation/TopNavigation.jsx
- src/pages/LoadingPage/LoadingPage.jsx
- src/pages/LoadingPage/index.js
- src/pages/RegisterPage/index.js
- src/pages/index.js
- src/router.js
#98
<br>
-로딩 페이지 생성
- 로그인버튼 추가
<br>
<br>
> feat: #98 구글 로그인을 위한 페이지 추가, API 연결

- src/components/TopNavigation/TopNavigation.jsx
> modify: #98 redirect_uri 수정

- src/pages/LoadingPage/LoadingPage.jsx
#98 
<br>
-구글 로그인 navigate 주소 변경
<br>
<br>
> modify: #98 navigate 주소 변경

- src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
#268
<br>
- 출석체크 페이지 내 다이얼 hover 효과 제거
- 모바일 및 태블릿PC 화면에 hover 효과 잔상이 남는 문제 해결
<br>
- 화면 동일
<br>
> #268 design: 출석체크 페이지 내 다이얼 hover 효과 제거

- src/pages/DetailStatisticsPage/CompletionChart.jsx
- src/pages/DetailStatisticsPage/DepartmentChart.jsx
- src/pages/DetailStatisticsPage/DetailStatisticsPage.jsx
- src/pages/DetailStatisticsPage/MajorChart.jsx
- src/pages/DetailStatisticsPage/YearChart.jsx
- src/pages/DetailStatisticsPage/attendee.js
#234
<br>
- 차트 디자인 일부 수정
- 학번, 전공별 전체 인원 세는 코드는 추후 수정 필요
<br>
|     세부 통계     |
| <img width='600' src='https://github.com/user-attachments/assets/028d69ec-4b6e-48e0-ab50-68e21e39b281'> |
<br>
> #234 modify: chart 디자인 일부 수정

- src/axios/axiosInstance.js
- src/components/TopNavigation/TopNavigation.jsx
- src/pages/LoadingPage/LoadingPage.jsx
- src/pages/LoadingPage/LoadingPage.style.js
#273 
<br>
- 로그인 / 회원가입 버튼 시 구글 로그인으로 연결
- 리다이렉트 -> 로딩 중 페이지에서 로그인 / 회원가입 api 연결
- axios 인터셉트로 accessToken 추가
<br>
<br>
> feat: #273 회원가입 및 로그인 기능 구현

- src/Pages/EventCardListPage/EventCardListPage.jsx
- src/Pages/EventCardListPage/EventCardListPage.style.jsx
- src/Pages/EventCardListPage/index.js
- src/apis/event.js
- src/axios/axiosInstance.js
- src/components/TopNavigation/TopNavigation.jsx
- src/pages/DashboardPage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/EventCardListPage/EventCardListPage.jsx
- src/pages/LoadingPage/LoadingPage.jsx
- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
- src/pages/registerPage/PageComponents/RegisterSecond.jsx
#273 
<br>
-api 구조 / 주소 일부 수정
<br>
<br>
> modify: #273 api 연결 주소 및 페이로드 수정

- src/components/TopNavigation/TopNavigation.jsx
> #278 [REFACTOR] 환경변수 env로 관리

- src/components/EventCard/EventCard.style.jsx
#285
<br>
- 행사 예정인 경우 글자 색상 red계열로 변경
<br>
| <img width='600' src='https://github.com/user-attachments/assets/a3d2f683-642a-454b-8069-9b8bcb2f0b2c'> |
<br>
> #285 design: 행사 예정인 경우 글자 색상 red계열로 변경

- src/components/Sidebar/Sidebar.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
- src/pages/DashboardPage/index.js
- src/pages/index.js
- src/router.js
#290
<br>
- 불필요한 코드 삭제 및 변경
<br>
- 변경 사항 없음
> #290 remove: 불필요한 코드 삭제 및 변경

- src/components/GraphBox/GraphBox.jsx
- src/components/GraphBox/GraphBox.style.js
- src/pages/TotalStatisticsPage/GraphChart.jsx
- src/pages/TotalStatisticsPage/TableChart.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
#247 
<br>
- 그래프 차트 컴포넌트 구현
- 모바일에서 Legend 부분을 숨김 처리
<br>
| ![image](https://github.com/user-attachments/assets/8f191f39-caf2-42b4-a45d-55e91710bb3b) |
| ![image](https://github.com/user-attachments/assets/2a4b0909-d6b4-4b31-86ef-833350457940) | <img width='250' src=''> |
<br>
> #247 feat: 그래프 차트 컴포넌트 구현

- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
- src/pages/registerPage/PageComponents/RegisterSecond.jsx
#293
<br>
- 행사 주소 입력 칸 추가
<br>
| ![image](https://github.com/user-attachments/assets/a739fbfe-9641-4ccd-bf42-3b40e5ffb4ab) |
<br>
> #293 feat 행사 주소 입력칸 추가

- src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
#297 
<br>
- 행사 기본 정보 오류 해결
- 행사 일정 컴포넌트 적용
- 변경 사항이 없을 경우 '저장하기' 버튼 비활성화
<br>
|     행사 기본 정보     |
| <img width='600' src='https://github.com/user-attachments/assets/ef2ea2f6-0cc4-4222-b914-2ead1ee69529'> |
<br>
> #297 fix: 행사 기본 정보 오류 해결

- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
#299
<br>
- 설문조사 링크 UI 구현
<br>
|     설문조사 링크 발송 페이지    |
| <img width='600' src='https://github.com/user-attachments/assets/13de7113-52e2-4d9c-9a66-ba67c4661d6a'> |
<br>
> #299 feat: 설문조사 링크 UI 구현

- src/components/Textarea/Textarea.jsx
- src/components/Textarea/Textarea.style.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
#300
<br>
- 리마인드 메일 발송 페이지 UI 수정
- Textarea 컴포넌트 수정 (기본 높이 100px)
<br>
|     리마인드 메일 발송 페이지     |
| <img width='600' src='https://github.com/user-attachments/assets/2874fcfb-60dd-403d-8036-f130a600db4d'> |
<br>
> #300 modify: email UI 수정

- src/components/DaterangePicker/DaterangePicker.style.js
- src/components/Table/Table.style.jsx
- src/components/Table/TotalStatisticsTable.jsx
- src/components/Table/index.js
- src/pages/TotalStatisticsPage/GraphChart.jsx
- src/pages/TotalStatisticsPage/TableChart.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
- src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
#247 
<br>
-전체 통계의 표 차트 구현
<br>
<br>
> #247 feat: 전체 통계 표 차트 구현

- src/pages/Home/Home.jsx
#110
<br>
- 주소 오류 수정
<br>
<br>
> #110 fix: 이동 주소 수정

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/EventCard/EventCard.jsx
- src/components/Sidebar/Sidebar.jsx
- src/components/TopNavigation/TopNavigation.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/router.js
#292
<br>
- 라우터 event > events로 수정
<br>
- 변경 사항 없음
<br>
> #292 modify: 라우터 event > events로 수정

- src/apis/event.js
#313
<br>
- API path 내 오타 수정
<br>
> #313 [FIX] API path 내 오타 수정

- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
#292
<br>
- 참석자 관리 페이지 오류 수정
- 참석자 정보 가져오는 기능 구현
<br>
|     참석자 관리 페이지     |
| <img width='600' src='https://github.com/user-attachments/assets/8e06b7ab-531e-4fd1-9d2c-fda998bdd4c4'> |
<br>
> #292 fix: 참석자 관리 페이지 오류 수정 및 참석자 정보 가져오는 기능 구현

- src/components/Table/AttendeeTable.jsx
- src/pages/DashboardPage/DashboardAttendeePage/AttendeeSearch.js
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
#318
<br>
- 테이블에 출석시간 추가
- 출석 시간 포맷팅 (HH:MM)
<br>
> #318 feat: 테이블에 출석시간 추가

- src/services/privateRoute/PrivateRoute.jsx
#320
<br>
- 로그인 정보 없을 시 리디렉션을 홈 -> 구글 로그인 페이지로 바로 넘어가도록 수정
<br>
<br>
> #320 feat: 리디렉션 주소 변경

- src/apis/attendance.js
- src/apis/event.js
- src/components/Dropdown/Dropdown.style.jsx
- src/components/Sidebar/Sidebar.jsx
- src/components/Table/AttendeeTable.jsx
- src/components/Table/Table.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
- src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
- src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/pages/DashboardPage/DashboardStatisticPage/CompletionChart.jsx
- src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.jsx
- src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.style.jsx
- src/pages/DashboardPage/DashboardStatisticPage/MajorChart.jsx
- src/pages/DashboardPage/DashboardStatisticPage/YearChart.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
#326
<br>
- api 및 페이지 내용 일부 수정
<br>
> #326 fix: api 및 페이지 내용 일부 수정

- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
#321
<br>
- API 스펙 맞춰 wise 주소 + 알림 체크박스 삭제
- 온라인 버전 시 드롭다운 아닌 최소 기준 시간 (분 단위)로 기
<br>
| ![image](https://github.com/user-attachments/assets/98b2a514-d195-472a-93d5-cdb5358432cb) |
<br>
> #321 modify: API 스펙 변경 + 온라인 버전 시 최소 이수 기준 인풋 구현

- src/components/TopNavigation/TopNavigation.jsx
#328
<br>
- 기존 로그아웃 코드 삭제
<br>
<br>
> #328 remove: 불필요 코드 삭제

- src/Pages/EventCardListPage/EventCardListPage.jsx
- src/pages/EventCardListPage/EventCardListPage.jsx
> #326 fix: 이벤트 목록 api 수정

- src/pages/LoadingPage/LoadingPage.jsx
#342
<br>
- 회원가입 API를 쿼리로 수정
<br>
<br>
> #342 fix: signup API 쿼리로 수정

- src/components/GraphBox/GraphBox.style.js
- src/pages/TotalStatisticsPage/EventsGraphChart.jsx
- src/pages/TotalStatisticsPage/EventsGraphChart.style.js
- src/pages/TotalStatisticsPage/GraphChart.jsx
- src/pages/TotalStatisticsPage/GraphChart.style.js
- src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
#247
<br>
- 참석률 높은 행사 TOP 3 구현
- 아직 미구현 된 기능인 스케줄러 제외
- 기존 막대 그래프 UI 일부 수
<br>
|![image](https://github.com/user-attachments/assets/e2534968-ad90-4ce4-b1ff-aaa1b837911c) |
| ![image](https://github.com/user-attachments/assets/9f7e3126-32b3-4621-9e7e-6ef17d0716f7) | <img width='250' src=''> |
<br>
> #247 feat: 참석률 높은 행사 TOP 3 구현

- src/components/UploadBox/UploadBox.jsx
- src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
#354
<br>
- 이미지일 경우에는 파일 이름 없이 미리보기
- 엑셀 파일 일 경우 안내 문장과 파일 이름 표시
<br>
| ![image](https://github.com/user-attachments/assets/757146fb-e622-44e3-92ae-fc18c1f8eae6) |
<br>
> #354 fix: 엑셀 파일 업로드 시 오류 수정

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/Table/TotalStatisticsTable.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
- src/pages/DashboardPage/DashboardPage.jsx
- src/pages/DashboardPage/DashboardPage.style.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
#352
<br>
- dashboard 내 api 수정 및 UI 추가
<br>
> #352 fix: dashboard 내 api 수정 및 UI 추가

- src/components/Modal/Modal.style.jsx
- src/components/Table/AttendeeTable.jsx
- src/components/Table/TotalStatisticsTable.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
#357
<br>
- 참석자 관리 페이지 내 모달창 생성 및 추가/삭제 UI 구현
- 테이블(`참석자 관리`, `전체통계`) 내 `휴대폰 번호`, `이메일` 항목 삭제
<br>
|     참석자 관리 페이지    |
| <img width='600' src='https://github.com/user-attachments/assets/4d76bdf6-d707-4b72-a84e-6be48e8caa46'> |
|     참석자 추가 모달    |
| <img width='600' src='https://github.com/user-attachments/assets/dc1f95b5-9609-455b-aeef-d0bf69faef4f'> |
<br>
> #357 feat: 참석자 관리 페이지 내 모달창 생성 및 추가/삭제 UI 구현

- src/components/AttendanceHeader/AttendanceHeader.jsx
- src/components/TopNavigation/TopNavigation.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage/UpdateAttendeeModal.js
- src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
- src/pages/registerPage/PageComponents/RegisterSecond.jsx
#352
<br>
-  내/외부 행사, 온/오프라인 상태에 따른 모달 내용 수정
-  x아이콘 누르면 참석자 관리 페이지로 이동
- 모달창 파일 분리
<br>
<br>
> #352 modify: 참석자 관리 페이지 내 모달창 일부 및 디테일 수정

- src/apis/index.js
- src/apis/mail.js
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
> #362 feat: mail 기능구현

- src/apis/attendance.js
- src/apis/mail.js
- src/components/Table/AttendeeTable.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage/UpdateAttendeeModal.js
- src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
- src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
#352
<br>
- 메일 기능 및 참석자 추가/삭제 기능
<br>
> #352 fix: 메일 기능 및 참석자 추가/삭제 기능

- src/pages/DashboardPage/DashboardPage.jsx
#367
<br>
- 행사 담당자 부분 임시 수정
<br>
|     대시보드     |
| <img width='600' src='https://github.com/user-attachments/assets/7b603a4c-a2a7-49e2-bceb-3f4b13a971e4'> |
\\
<br>
> #367 feat: 행사 담당자 부분 임시 수정

- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
- src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
- src/pages/DashboardPage/DashboardAttendeePage/LogAnalyzeButton.jsx
#363
<br>
- 온라인 행사인 경우에만 줌 로그를 분석하는 파일 + 분석 버튼 구
<br>
| ![image](https://github.com/user-attachments/assets/bd5d47db-8575-4910-81ba-1a45ce1264e8) |
<br>
> #363 feat: 줌 로그 분석 구현

- src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
- src/pages/registerPage/PageComponents/RegisterSecond.jsx
#371
<br>
- 템플릿 제대로 잘 다운받아지게 수정 완료
<br>
<br>
> #371 fix: 템플릿 다운로드 에러 수정

- src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
- src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
#369
<br>
- 출석체크시 휴대폰 번호 뒷자리가 중복될 경우 띄워줄 모달창 구현
<br>
|     학번 입력 후 모달창     |
| <img width='600' src='https://github.com/user-attachments/assets/43164b2b-4dc4-43b0-9c8e-89f8d99d9208'> |
<br>
> #369 fix: 출석체크시 휴대폰 번호 뒷자리가 중복될 경우 띄워줄 모달창 구현
